#!/bin/bash

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nano'
else
  export EDITOR='subl'
fi

# ZSH
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Nicer history
export HISTSIZE=100000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

# If you press v during viewing file with less utility, it'll open an editor.
# You can choose the editor by setting LESSEDIT variable. For example:
export LESSEDIT='subl %f'

# SOURCE HIDDEN VERSION
source_hidden_dotfiles "exports"
